---
cidr_networks:
  container: 172.16.16.0/24
  tunnel: 172.16.17.0/24
  storage: 172.16.18.0/24

used_ips:
  - "172.16.16.1,172.16.16.14"
  - "172.16.17.1,172.16.17.10"
  - "172.16.18.1,172.16.18.10"

global_overrides:
  internal_lb_vip_address: 172.16.16.9
  #
  # The below domain name must resolve to an IP address
  # in the CIDR specified in haproxy_keepalived_external_vip_cidr.
  # If using different protocols (https/http) for the public/internal
  # endpoints the two addresses must be different.
  #
  external_lb_vip_address: 172.16.16.10
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "mgmt"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "vxlan"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-provider"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth0"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "storage"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# load balancer

haproxy_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# rsyslog server
log_hosts:
  log1:
    ip: 172.16.16.12

### 
### Ceph
###

# OSD nodes
ceph-osd_hosts:
  osd1:
    ip: 172.16.16.6
  osd2:
    ip: 172.16.16.7
  osd3:
    ip: 172.16.16.8

# ceph-mon containers
ceph-mon_hosts: 
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# ceph-mds containers
ceph-mds_hosts: 
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# ganesha-nfs hosts
ceph-nfs_hosts: 
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

###
### OpenStack
###

# keystone
identity_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# cinder api services
storage-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# glance
image_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

storage_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# placement
placement-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# nova api, conductor, etc services
compute-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# heat
orchestration_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# horizon
dashboard_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# neutron api
# network-infra_hosts:
#   controller1:
#     ip: 172.16.16.2
#   controller2:
#     ip: 172.16.16.3
#   controller3:
#     ip: 172.16.16.4

network_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# neutron agents (L3, DHCP, etc)
# network-agent_hosts:
#   controller1:
#     ip: 172.16.16.2
#   controller2:
#     ip: 172.16.16.3
#   controller3:
#     ip: 172.16.16.4

# ceilometer (telemetry data collection)
metering-infra_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# aodh (telemetry alarm service)
metering-alarm_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# gnocchi (telemetry metrics storage)
metrics_hosts:
  controller1:
    ip: 172.16.16.2
  controller2:
    ip: 172.16.16.3
  controller3:
    ip: 172.16.16.4

# nova hypervisors
compute_hosts:
  compute-01:
    ip: 172.16.16.5


# ceilometer compute agent (telemetry data collection)
metering-compute_hosts:
  compute-01:
    ip: 172.16.16.5